export const projects = {
  "https://devfolio.co/submissions/karobari-5133": {
    "Project Name": "KAROBARI",
    Description:
      "1.Securing Funding: Founders struggle to attract investors and secure capital for growth. 2.Networking and Relationship Building: Founders face difficulty in accessing relevant networks, building meaningful relationships, and leveraging them for growth and collaboration. 3.Navigating Legal Landscape: Founders encounter challenges in navigating complex legal landscapes, hindering compliance, protecting intellectual property, and mitigating legal risks. 4.Accessing Government Schemes and Industry News: Founders find it challenging to access vital government schemes and stay updated on relevant industry news affecting their business.",
    "Technologies Used": [
      "Docker",
      "Figma",
      "Express.js",
      "MongoDB",
      "MERN stack",
      "Docker",
      "Figma",
      "Express.js",
      "MongoDB",
      "MERN stack",
    ],
    "Team Name": "Gazak",
    "GitHub Link": "https://github.com/OAtulA/Karobari_alpha",
  },
  "https://devfolio.co/submissions/safecom-6182": {
    "Project Name": "SafEcom",
    Description:
      "Our solution revolves around the comprehensive detection and prevention of dark patterns on e-commerce websites, safeguarding users from deceptive practices in user interfaces, subscription processes, product information, account creation, urgency and scarcity claims, hidden costs, and user reviews. Employing a multi-faceted approach, our system leverages advanced technologies such as computer vision, natural language processing (NLP), machine learning, and web scraping to ensure a robust and proactive defense against a wide array of deceptive\u00a0tactics.",
    "Technologies Used": [
      "HTML",
      "React",
      "CSS",
      "JavaScript",
      "Flask",
      "TensorFlow",
      "Selenium",
      "Python",
      "Nodejs",
      "LLM",
      "HTML",
      "React",
      "CSS",
      "JavaScript",
      "Flask",
      "TensorFlow",
      "Selenium",
      "Python",
      "Nodejs",
      "LLM",
    ],
    "Team Name": "Darkine",
    "GitHub Link": "https://github.com/Atulit23/final_extension",
  },
  "https://devfolio.co/submissions/lifeflow-b613": {
    "Project Name": "Lifeflow",
    Description:
      'Our solution "LifeFlow" is a mobile application designed to help connect people in urgent need of blood with their prospective donor, which might be an individual, blood bank or a hospital. Donors can post their details (blood group, age, sex and medical history) and their locations, they can directly register on the app, or the blood bank / hospital they donate to will post their details based on their consent. The recipients can browse through the donors and based on their locations and medical history, select a donor. If no donor is found at that instance, we will notify the user whenever there is a prospective match, we also notify a frequent donor for help in case there is a medical emergency in their nearby location. Organizations that conduct blood donation drives can register on our app, so that we can notify frequent donors living nearby.',
    "Technologies Used": [
      "React Native",
      "Frontend: React Js",
      "Backend: FastAPI",
      "External API: Google Maps API",
      "Messaging Queue: Kafka/RabbitMQ",
      "Mobile Notifications: Firestore Messaging",
      "Database: MySQL/MongoDB",
      "Caching: Redis",
      "React Native",
      "Frontend: React Js",
      "Backend: FastAPI",
      "External API: Google Maps API",
      "Messaging Queue: Kafka/RabbitMQ",
      "Mobile Notifications: Firestore Messaging",
      "Database: MySQL/MongoDB",
      "Caching: Redis",
    ],
    "Team Name": "Autonomous Cleaners",
    "GitHub Link": "https://github.com/mVedr/lifeflow_backend/",
  },
  "https://devfolio.co/submissions/surviliance-system-0229": {
    "Project Name": "Surviliance System",
    Description:
      "Our application serves as a vital tool for government security agencies, enabling them to upload photos of individuals considered threats to public gatherings or those evading law enforcement. Using AI technology, the system scans uploaded images to detect faces accurately. Upon uploading, the agency receives a unique link accessible on smartphones worldwide. When accessed, the smartphone transforms into a surveillance camera. If any activity is detected in the camera's vicinity, the system immediately sends real-time location data and images of the individual to the central agency. This ensures swift action in apprehending suspects. Moreover, if the suspect moves to another location and triggers a different camera, the system creates a comprehensive trail of the suspect's movements. Importantly, access to this sensitive location and image data is restricted solely to authorized personnel within the central agency, ensuring confidentiality and security.",
    "Technologies Used": [
      "Flask",
      "OpenCV",
      "Firebase Authentication",
      "React.js",
      "Face Recognition",
      "TailWindCSS",
      "Flask",
      "OpenCV",
      "Firebase Authentication",
      "React.js",
      "Face Recognition",
      "TailWindCSS",
    ],
    "Team Name": "Anonymous R-Evil",
    "GitHub Link": "https://github.com/Abhikumar9896/HackHazard",
  },
  "https://devfolio.co/submissions/citysync-dad6": {
    "Project Name": "CitySync",
    Description:
      "Problem Title: Smart Traffic ManagementProblem Description:Develop a Smart Traffic Management and Optimization System that utilizes data-driven insights, predictive analytics, and real-time monitoring to improve traffic flow, alleviate congestion, and enhance the overall transportation experience in urban areas. The system should integrate with existing infrastructure and provide actionable recommendations to traffic authorities for proactive decision-making and intervention.",
    "Technologies Used": [
      "Go",
      "JavaScript",
      "Pygame",
      "Python",
      "CSS3",
      "HTML5\u200b",
      "telegramAPI",
      "XXNetwork",
      "Go",
      "JavaScript",
      "Pygame",
      "Python",
      "CSS3",
      "HTML5\u200b",
      "telegramAPI",
      "XXNetwork",
    ],
    "Team Name": "Phoenix Flames",
    "GitHub Link": "https://github.com/vishal1mittal/CitySync",
  },
  "https://devfolio.co/submissions/qlearn-a-gamified-d-learning-platform-13b9":
    {
      "Project Name": "Q-Learn: A Gamified 3D Learning Platform",
      Description:
        "PROBLEMSPassivity and boredom: Lectures, textbooks, and rote memorization can feel passive and fail to ignite a genuine interest in the subject matter.Lack of interaction: Limited opportunities for collaboration and interaction with peers can hinder knowledge sharing and a sense of community.Difficulties in motivation: Traditional methods often lack inherent rewards or gamified elements, making it challenging for students to maintain motivation over time.Limited accessibility of resources: Students may not have easy access to a variety of engaging learning materials, such as interactive websites, video tutorials, and personalized assistance.",
      "Technologies Used": [
        "React",
        "scikit-image",
        "Python",
        "Blender",
        "TypeScript",
        "C#",
        "Unity 3D",
        "Vercel",
        "Streamlit",
        "Coherence",
        "React",
        "scikit-image",
        "Python",
        "Blender",
        "TypeScript",
        "C#",
        "Unity 3D",
        "Vercel",
        "Streamlit",
        "Coherence",
      ],
      "Team Name": "Darkcoders",
      "GitHub Link":
        "https://github.com/AshishMittal33/Q-Learn-3D-virtual-platform-",
    },
  "https://devfolio.co/submissions/shilded-penni-8dc2": {
    "Project Name": "Shilded penni",
    Description:
      "1.Scams in centralize system2.unsatble Cryptocurrency and markets3.lack of finance awareness",
    "Technologies Used": [
      "Vue.js",
      "REST API",
      "WebSockets",
      "MySQL",
      "Web3",
      "Blockchain",
      "Brownie",
      "Hardhat",
      "deap learning",
      "Vue.js",
      "REST API",
      "WebSockets",
      "MySQL",
      "Web3",
      "Blockchain",
      "Brownie",
      "Hardhat",
      "deap learning",
    ],
    "Team Name": "khufiya-watermelon",
    "GitHub Link": "https://github.com/Vishal8700/Shielded-penni",
  },
  "https://devfolio.co/submissions/secure-pay-a430": {
    "Project Name": "Secure Pay",
    Description:
      "Our project aims to address the challenge of financial fraud in the age of finance by developing a decentralized finance (defi) called SecurePay. In today's financial era, Account Takeover Fraud(ATO) is the most common form of identity theft where fraudsters overtake an online account and pose as real users. Typical means for ATO include compromised credentials SIM card Swap, Session Hijacking, Social Engineering and device takeover. These attacks are also known as Man-in-the-middle(MITM) Attacks. SecurePay seeks to tackle this issue by using a decentralized transaction system. As the name suggests every transition is not controlled or authorized by one authority. The SecurePay will allow the users to send money anonymously and transactions will be secured on the blockchain network.",
    "Technologies Used": [
      "Next.js",
      "Solana pay(SOL)",
      "XX Network",
      "Next.js",
      "Solana pay(SOL)",
      "XX Network",
    ],
    "Team Name": "Valorous_Coders",
    "GitHub Link": "https://secure-pay-lhd4.vercel.app/",
  },
  "https://devfolio.co/submissions/guardianvault-9e18": {
    "Project Name": "GuardianVault",
    Description:
      "This project empowers users, including public sectors, to efficiently organize their documents, whether handling individual files or bulk document management. Notably, it enhances document security through encryption, ensuring unparalleled safety. This feature assures users that their sensitive information remains safeguarded, contributing to peace of mind and compliance with data protection standards. By offering seamless organization and enhanced security measures, this solution revolutionizes document management practices, catering to diverse user needs and organizational requirements.",
    "Technologies Used": [
      "React",
      "Firebase",
      "TensorFlow",
      "Python",
      "Figma",
      "GIMP",
      "Tailwind CSS",
      "React",
      "Firebase",
      "TensorFlow",
      "Python",
      "Figma",
      "GIMP",
      "Tailwind CSS",
    ],
    "Team Name": "Code$trikers",
    "GitHub Link": "https://github.com/Prayag2/guardianvault",
  },
  "https://devfolio.co/submissions/eduverse-09e0": {
    "Project Name": "EDUVERSE",
    Description:
      "There are many problems that we are tackling currently through our platform:Gamified edtech solutions face inefficiencies due to reduced retention caused by excessive visual elements. While they aim to boost engagement, collaboration suffers as competition prevails.Moreover, these platforms lack immersive interactivity, hindering deep learning experiences. To be effective, gamified edtech must balance visual appeal with educational content, foster collaboration, and offer immersive interactions for meaningful learning outcomes.",
    "Technologies Used": [
      "ARCore",
      "Vuforia",
      "VR",
      "Blender",
      "Web3",
      "WordPress",
      "Unity 3D",
      "Web development",
      "Generative AI",
      "ARCore",
      "Vuforia",
      "VR",
      "Blender",
      "Web3",
      "WordPress",
      "Unity 3D",
      "Web development",
      "Generative AI",
    ],
    "Team Name": "pechkas",
    "GitHub Link": "https://github.com/IshaanMinocha/eduverse_hackhazards",
  },
  "https://devfolio.co/submissions/forensic-eye-dbee": {
    "Project Name": "Forensic eye",
    Description:
      "Image and Video Analysis: Use advanced algorithms to analyze inconsistencies, artifacts, and anomalies in both image and video content. This can involve detecting unnatural facial movements, inconsistent lighting, or mismatched audio.Machine Learning Models: Train machine learning models on large datasets of both real and fake media to recognize patterns and features indicative of deepfakes. Techniques like convolutional neural networks (CNNs) are commonly used for this purpose.Forensic Analysis: Employ forensic techniques such as examining metadata, analyzing compression artifacts, and studying pixel-level details to distinguish between genuine and manipulated media.Biometric Verification: Incorporate biometric verification methods like facial recognition or voice analysis to authenticate the identities of individuals in media content.Blockchain Technology: Utilize blockchain to establish a tamper-proof record of media provenance, ensuring that content hasn't been altered since its creation.Collaborative Databases: Build and maintain collaborative databases where researchers and experts can share deepfake samples, algorithms, and detection methods to continually improve detection capabilities.User Education and Awareness: Educate users about the existence and potential risks of deepfakes, encouraging skepticism and critical thinking when consuming media content.Regulatory Measures: Advocate for regulations and policies to address the creation and dissemination of deepfakes, potentially holding platforms accountable for hosting malicious content.Real-time Monitoring Systems: Develop real-time monitoring systems that can quickly flag suspicious media content as it emerges online, allowing for rapid response and mitigation.Hybrid Approaches: Combine multiple techniques and solutions to create robust deepfake detection systems that can adapt to evolving threats and techniques used by malicious actors.",
    "Technologies Used": [
      "Flask",
      "Python",
      "Convolutional neural network (CNN)",
      "Flask",
      "Python",
      "Convolutional neural network (CNN)",
    ],
    "Team Name": "Forensic eye",
    "GitHub Link": "https://github.com/kavyapurohit/forensic-eye",
  },
  "https://devfolio.co/submissions/bloodbridge-4d00": {
    "Project Name": "BloodBridge",
    Description:
      "BloodBridge: Connecting Donors, Hospitals, and NGOs for Efficient Blood DonationHere's what you can tell the judges at your hackathon about BloodBridge:",
    "Technologies Used": [
      "Node.js",
      "Git",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "React.js",
      "Node.js",
      "Git",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "React.js",
    ],
    "Team Name": "H.A.R.D.",
    "GitHub Link": "https://github.com/Gojou0/BloodBridge.git",
  },
  "https://devfolio.co/submissions/crimsonconnect-ef6c": {
    "Project Name": "CrimsonConnect",
    Description:
      "In today's fast-paced world, access to timely and suitable blood donations can be a matter of life and death. Our project, CrimsonConnect, aims to address the critical challenges in the existing blood donation ecosystem by creating a transparent and user-friendly platform that facilitates seamless connections between blood donors and recipients while ensuring data privacy through the use of Blockchain technology.",
    "Technologies Used": [
      "Solidity",
      "Node.js",
      "Django",
      "JavaScript",
      "Ethereum TestRPC",
      "Leaflet.js",
      "React.js",
      "Hardhat",
      "Polygon Mumbai Testnet",
      "xx-network",
      "Solidity",
      "Node.js",
      "Django",
      "JavaScript",
      "Ethereum TestRPC",
      "Leaflet.js",
      "React.js",
      "Hardhat",
      "Polygon Mumbai Testnet",
      "xx-network",
    ],
    "Team Name": "Clash of codes",
    "GitHub Link":
      "https://github.com/PranavPC2003/Crimson-Connect/tree/master",
  },
  "https://devfolio.co/submissions/watchguard-09b1": {
    "Project Name": "WatchGuard",
    Description:
      "The project's goal is to improve surveillance systems by automatically identifying dangers and rule-breaking actions using Python backend technologies and machine learning (ML). The technology may quickly identify many kinds of threats, such as armed revolt, unlawful access, or rule infractions, by analyzing live footage from surveillance cameras. When a threat is detected, the system will make sure that everyone is informed by categorically customizing notifications according on how serious the threat is. For example, instant WhatsApp notifications of armed insurrection will be sent to all workers, students, and employees when immediate action is needed. The notifications will include live\u00a0imagery of the criminal. On the other hand, through designated routes, less critical matters will be communicated to the local police authority or the security department of the\u00a0organisation.",
    "Technologies Used": [
      "React",
      "Django",
      "OpenCV",
      "Machine Learning",
      "Python",
      "ONNX",
      "axios",
      "YOLO",
      "React",
      "Django",
      "OpenCV",
      "Machine Learning",
      "Python",
      "ONNX",
      "axios",
      "YOLO",
    ],
    "Team Name": "Ark Alpha",
    "GitHub Link": "https://github.com/AzeemIdrisi/WatchGuard",
  },
  "https://devfolio.co/submissions/empowering-timely-donations-8922": {
    "Project Name": "Empowering Timely Donations",
    Description:
      "Its is not just a platform; it's a lifeline that redefines the blood donation experience. Our unique business model integrates corporate social responsibility (CSR) initiatives with a compelling unique selling proposition (USP) to drive impact. By partnering with hospitals, we offer donors exclusive perks such as coupons and free healthcare facilities, strengthening community engagement and incentivizing participation. Overall, our platform addresses critical challenges in the blood donation ecosystem by providing a user-friendly, secure, and efficient platform that connects donors, patients, and healthcare facilities. Through its innovative features and capabilities, the platform not only makes the blood donation process more accessible and convenient but also ensures the safety and reliability of blood transfusions, ultimately saving lives and improving healthcare outcomes. It's more than a platform; it's a movement towards a healthier, more connected world.",
    "Technologies Used": [
      "Bootstrap",
      "Firebase",
      "JavaScript",
      "SCSS",
      "Google API",
      "Netlify",
      "Tailwind CSS",
      "React.js",
      "HTML5\u200b",
      "Bootstrap",
      "Firebase",
      "JavaScript",
      "SCSS",
      "Google API",
      "Netlify",
      "Tailwind CSS",
      "React.js",
      "HTML5\u200b",
    ],
    "Team Name": "umangTrio",
    "GitHub Link": "https://github.com/raashimathur/bloodDonation",
  },
  "https://devfolio.co/submissions/maester-on-duty-3e9e": {
    "Project Name": "Maester on duty",
    Description:
      "Our project aims to create a transparent blood donation ecosystem to ensure timely patient care. Through this platform, donors can register and provide details about their blood type, location, and availability. Hospitals and blood banks can then access this information to quickly locate suitable donors in their vicinity. The system will incorporate real-time updates on blood inventory levels, donation events, and urgent requests. Additionally, it will facilitate communication between donors and recipients, fostering a sense of community and accountability. By promoting transparency and efficiency, our platform aims to bridge the gap between blood supply and demand, ultimately saving lives and improving healthcare outcomes. Our project is creating a website to make it easy for people to donate blood and help patients quickly. Donors can sign up and say when they're available to give blood. Hospitals and blood banks can then find donors nearby easily. The website will also show how much blood is available in real-time and if there are any urgent needs. It will also let donors and patients talk to each other. Our goal is to make donating blood straightforward, make sure there's enough blood for patients, and save lives by getting blood to those who need it fast.",
    "Technologies Used": [
      "HTML",
      "CSS",
      "JavaScript",
      "GitHub",
      "Express.js",
      "MongoDB",
      "Node",
      "conductor repository",
      "HTML",
      "CSS",
      "JavaScript",
      "GitHub",
      "Express.js",
      "MongoDB",
      "Node",
      "conductor repository",
    ],
    "Team Name": "Sasta Hogwards",
    "GitHub Link": "https://github.com/shreyashsing/hackhazards",
  },
  "https://devfolio.co/submissions/revolutionizing-blood-management-3dd6": {
    "Project Name": "Revolutionizing Blood Management",
    Description:
      "OurProject, a dynamic web application, tackles inefficiencies in blood management with a user-friendly approach. It features secure login and registration for Blood Banks, Hospitals, and Blood Donors, offering personalized profiles and a rewarding points system for active participants. Blood Banks input real-time data on blood availability, generate certificates, and efficiently allocate resources to fulfill hospital requests.",
    "Technologies Used": [
      "Solidity",
      "PHP",
      "React",
      "HTML5",
      "CSS3",
      "MongoDB",
      "Nodejs",
      "Express",
      "Solidity",
      "PHP",
      "React",
      "HTML5",
      "CSS3",
      "MongoDB",
      "Nodejs",
      "Express",
    ],
    "Team Name": "Codeverse",
    "GitHub Link": "https://github.com/himanshu562/Blood_bank",
  },
  "https://devfolio.co/submissions/dhansavvy-668d": {
    "Project Name": "DhanSavvy",
    Description:
      "We solves the problem of youngster and beginners in the phase of investing and budgeting by educating and keeping the track of their expenses and savings and telling them best investments startegy through AI model according to their risk appetite and this will make them earn and invest more in future and also they will also beat the inflation rate of 6% annually by generating almost of 15% of ROI and creating awareness about finance in youth.",
    "Technologies Used": [
      "Firebase",
      "TypeScript",
      "OpenAi",
      "Material-UI",
      "reactjs",
      "Replit",
      "Vite",
      "GOOGLE AI STUDIO",
      "MPT",
      "Amazon ce2 server",
      "Firebase",
      "TypeScript",
      "OpenAi",
      "Material-UI",
      "reactjs",
      "Replit",
      "Vite",
      "GOOGLE AI STUDIO",
      "MPT",
      "Amazon ce2 server",
    ],
    "Team Name": "Teen Jaadu",
    "GitHub Link": "https://github.com/apoorva-01/Dhan-Savvy",
  },
  "https://devfolio.co/submissions/greenenv-8524": {
    "Project Name": "GreenEnv",
    Description: "...",
    "Technologies Used": [
      "Flutter",
      "Web3",
      "MERN stack",
      "Solana",
      "Flutter",
      "Web3",
      "MERN stack",
      "Solana",
    ],
    "Team Name": "coke",
    "GitHub Link": "https://github.com/HarshRaj2717/GreenEnv",
  },
  "https://devfolio.co/submissions/blood-bridge-b9d8": {
    "Project Name": "Blood Bridge",
    Description:
      "Blood Bridge addresses the critical issue of blood shortages and inadequate access to blood transfusions by creating an innovative platform that connects blood donors with recipients in need. With millions of lives at stake each year due to insufficient blood supply, Blood Bridge aims to revolutionize the way blood donations are facilitated, making the process more efficient, transparent, and accessible to all.Blood Bridge employs advanced algorithms to facilitate real-time matching between blood donors and recipients, ensuring timely access to life-saving blood transfusions.Blood Bridge operates with transparency and accountability, providing transparent information about blood donation needs, utilization, and impact, ensuring trust and credibility among users.Blood Bridge provides users with comprehensive information about the importance of blood donation, eligibility criteria, donation process, and post-donation care. This hub could include videos, infographics, and quizzes to engage users and increase awareness about\u00a0blood\u00a0donation.Blood Bridge prioritizes user privacy and security, implementing robust measures to safeguard personal information and maintain confidentiality throughout the donation process.",
    "Technologies Used": [
      "HTML",
      "Firebase",
      "CSS",
      "JavaScript",
      "API",
      "HTML",
      "Firebase",
      "CSS",
      "JavaScript",
      "API",
    ],
    "Team Name": "Bit Binders",
    "GitHub Link":
      "https://github.com/prabalaggarwal2003/prabalaggarwal2003.github.io",
  },
  "https://devfolio.co/submissions/ebye-7b61": {
    "Project Name": "E-Bye",
    Description:
      "Organisations can sell their e waste and get carbon credits for it, thus getting tax exemptions, amongst other things. Repair shops can buy trusted, vetted parts from us at a low cost",
    "Technologies Used": [
      "React",
      "MongoDB",
      "Tailwind CSS",
      "jsonwebtoken",
      "Express",
      "Node.",
      "Microsoft CoPilot Studio",
      "React",
      "MongoDB",
      "Tailwind CSS",
      "jsonwebtoken",
      "Express",
      "Node.",
      "Microsoft CoPilot Studio",
    ],
    "Team Name": "Pinaka",
    "GitHub Link": "https://github.com/tanaykmr/ebye/",
  },
  "https://devfolio.co/submissions/farfromhome-refugee-help-df7b": {
    "Project Name": "FarFromHome (Refugee Help)",
    Description:
      'Right now, the "Only" identity provided to refugees is by UNHCR and this is valid for 2 years only, also after the recent ongoing wars like that of Ukraine, Myanmar\'s military coups and other territorial conflicts have increased the percentage of Refugee influx in India, and the problem with tracking them also exists, Thus using Blockchain to both providing the refugees a bankless indentity as well as giving them financial security to sustain a living until they are eligible for a valid nationality to have a legal bank account. Blockchain provides decentralized, robust and immutable system that will help ensure their identity remains safe an secure, and also will be "ONE " of its own project to promote digital currency in India.',
    "Technologies Used": [
      "Solidity",
      "React",
      "JavaScript",
      "Ethereum",
      "Blockchain",
      "HTML/CSS",
      "Solidity",
      "React",
      "JavaScript",
      "Ethereum",
      "Blockchain",
      "HTML/CSS",
    ],
    "Team Name": "Legacy Code Corp.",
    "GitHub Link": "https://github.com/Siddharthis1/FFH_BPIT.git",
  },
  "https://devfolio.co/submissions/sehatsampark-c5e3": {
    "Project Name": "SehatSampark",
    Description:
      "SehatSampark offers a comprehensive solution for organizing and managing medical camps. Hospitals can schedule and manage camps through the platform, including assigning medical staff, scheduling appointments via Video Conefrencing, and managing patient data. Doctors can remotely consult with patients during the camps, while agents handle data recording, medication distribution, and prescription issuance. Customers can easily book in-person appointments simply via SMS and a toll-free IVR for distress calls to doctors. Customers will get camp alerts on SMS. The SMS-based booking system caters to users without internet access, allowing them to book appointments, receive camp notifications, and make emergency calls. Overall, SehatSampark streamlines camp organization, facilitates remote consultations, and fosters accessibility for both hospitals and patients in underserved\u00a0communities.",
    "Technologies Used": [
      "HTML",
      "MySQL",
      "Backend: Flask and Python\n\nFrontend: React",
      "Flask blueprints",
      "App: No-Code\n\nSMS API: Services of Twilio and Push Bullet SMS API.\n\nDatabase: MongoDB",
      "HTML",
      "MySQL",
      "Backend: Flask and Python\n\nFrontend: React",
      "Flask blueprints",
      "App: No-Code\n\nSMS API: Services of Twilio and Push Bullet SMS API.\n\nDatabase: MongoDB",
    ],
    "Team Name": "Chole Bhature Gang",
    "GitHub Link": "https://github.com/inaxia/Sehat-Sampark",
  },
  "https://devfolio.co/submissions/coinsavvy-dd48": {
    "Project Name": "CoinSavvy",
    Description:
      "The average loan student debt for students graduated from college in 2022 was $375,746The average college student has approximately $3,100 in credit card debt.Unfortunately, today\u2019s youth lack the trivial knowledge on money management like saving, spending, budgeting, responsible borrowing, investing etc. \u2018CoinSavvy\u2019 is an online platform to provide the youth with the necessary money management skills by promoting financial literacy. It will enable them to make wise short-term as well as long-term financial decisions and avoid excessive debt. This platform\u2019s ultimate objective is to make the youth financially stable and mindful individuals when it comes to managing expenses.",
    "Technologies Used": [
      "HTML",
      "Node.js",
      "CSS",
      "JavaScript",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "React.js",
      "HTML",
      "Node.js",
      "CSS",
      "JavaScript",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "React.js",
    ],
    "Team Name": "Hack Haven",
    "GitHub Link": "https://github.com/Kaushik20yash/cowbase.git",
  },
  "https://devfolio.co/submissions/finspire-0841": {
    "Project Name": "FinSpire",
    Description:
      "Our product simplifies finance for beginners, providing personalized investment guidance and real-time market insights, solving the complexity barrier.",
    "Technologies Used": [
      "Firebase",
      "REST API",
      "Flutter",
      "Figma",
      "CanvasJS",
      "Tailwind CSS",
      "Vercel",
      "nextjs",
      "orkes",
      "XXNetwork",
      "Firebase",
      "REST API",
      "Flutter",
      "Figma",
      "CanvasJS",
      "Tailwind CSS",
      "Vercel",
      "nextjs",
      "orkes",
      "XXNetwork",
    ],
    "Team Name": "Rookie Techies",
    "GitHub Link": "https://github.com/RookieTechies-FinSpire",
  },
  "https://devfolio.co/submissions/leaf-languageenabledacademic-forum-31db": {
    "Project Name": "L-E-A-F (Language-Enabled-Academic -Forum)",
    Description:
      "LEAF revolutionizes collaborative learning by transcending language barriers. It enables students from diverse linguistic backgrounds to seamlessly interact, share knowledge, and collaborate effectively. Whether in classrooms, group projects, or online discussions, LEAF fosters inclusive education by providing a platform where language is no longer a barrier to meaningful engagement and learning.",
    "Technologies Used": [
      "Node.js",
      "Visual Studio Code",
      "CSS",
      "Django",
      "JavaScript",
      "TensorFlow",
      "Python",
      "MongoDB",
      "React.js",
      "Node.js",
      "Visual Studio Code",
      "CSS",
      "Django",
      "JavaScript",
      "TensorFlow",
      "Python",
      "MongoDB",
      "React.js",
    ],
    "Team Name": "The L-E-A-F",
    "GitHub Link":
      "https://github.com/nikhilchauhan9812/Hackhazards2024-team-the-L-E-A-F-/tree/main/hackhazards24",
  },
  "https://devfolio.co/submissions/citadel-faea": {
    "Project Name": "Citadel",
    Description:
      "The rise of anonymous transactions and digital assets exposes individuals and organizations to increased risks of financial fraud, including scams and hacking.",
    "Technologies Used": [
      "Bootstrap",
      "React",
      "Infura",
      "Python",
      "Ethereum",
      "Bootstrap",
      "React",
      "Infura",
      "Python",
      "Ethereum",
    ],
    "Team Name": "Tech Squad",
    "GitHub Link": "https://github.com/sakshamSolanki/Citadel/",
  },
  "https://devfolio.co/submissions/ezypark-8e32": {
    "Project Name": "EzyPark",
    Description:
      "Deploying a website and integrating database models presented us with a set of challenges. However, with a strategic approach, we successfully navigated these obstacles. For the deployment process, we utilized two distinct services: Vercel.com for frontend deployment and Render.com for API deployment. To address the complexities of implementing data models, we conducted brainstorming sessions that led to effective solutions",
    "Technologies Used": [
      "Node.js",
      "SASS",
      "Redux",
      "JSON",
      "Express.js",
      "MongoDB Atlas",
      "axios",
      "Moment.js",
      "React.js",
      "Node.js",
      "SASS",
      "Redux",
      "JSON",
      "Express.js",
      "MongoDB Atlas",
      "axios",
      "Moment.js",
      "React.js",
    ],
    "Team Name": "TechMojo",
    "GitHub Link": "https://github.com/priyanshu102002/EzyPark",
  },
  "https://devfolio.co/submissions/flamingo-288f": {
    "Project Name": "Flamingo",
    Description:
      "Flamingo addresses the challenge of language barriers in diverse educational environments. It functions as a comprehensive platform for collaborative learning, empowering students with real-time translation tools, interactive whiteboards, and multilingual content libraries. This fosters seamless communication and knowledge exchange across languages.  Additionally, features like gamification and AI-powered language learning tools enhance student engagement and personalize learning experiences. Flamingo equips teachers with tools for managing multilingual classrooms and promoting intercultural understanding. Overall, Flamingo creates a more inclusive learning environment where students of all linguistic backgrounds can connect, collaborate, and thrive in a global classroom",
    "Technologies Used": [
      "Next.js",
      "Docker",
      "GitHub",
      "TypeScript",
      "MongoDB",
      "Tailwind CSS",
      "Express",
      "Recoil",
      "orkes",
      "Pinecone",
      "Next.js",
      "Docker",
      "GitHub",
      "TypeScript",
      "MongoDB",
      "Tailwind CSS",
      "Express",
      "Recoil",
      "orkes",
      "Pinecone",
    ],
    "Team Name": "Runtime Terror",
    "GitHub Link": "https://github.com/aakriti562/Flamingo",
  },
  "https://devfolio.co/submissions/codecommune-be5b": {
    "Project Name": "CodeCommune",
    Description:
      "The platform solves the problem of traditional, uninspiring programming education by offering an engaging, gamified approach. It addresses the lack of motivation, engagement, and practical application in conventional learning methods, making coding education more enjoyable, rewarding, and accessible for learners of all levels. Through 1v1 competitions and story-based quests, it encourages active participation, collaboration, and skill development, ultimately bridging the gap between theoretical knowledge and real-world proficiency in coding.",
    "Technologies Used": [
      "HTML",
      "React",
      "Firebase",
      "CSS",
      "tailwind",
      "HTML",
      "React",
      "Firebase",
      "CSS",
      "tailwind",
    ],
    "Team Name": "Nokturnuls",
    "GitHub Link": "https://github.com/MrRobot311204/CodeCommuneFinal",
  },
  "https://devfolio.co/submissions/empowering-health-b4de": {
    "Project Name": "Empowering Health",
    Description:
      "Empowering Health revolutionizes healthcare accessibility for remote communities through its innovative website solution. By seamlessly connecting individuals in remote areas with healthcare services, our platform ensures easy access to medical consultations, diagnosis, and treatment. With a user-friendly interface and a network of healthcare providers, Empowering Health empowers individuals to prioritize their health regardless of geographical barriers.",
    "Technologies Used": [
      "Ethereum",
      "Blockchain",
      "Ganache",
      "Remix (IDE)",
      "React.js",
      "Ethereum",
      "Blockchain",
      "Ganache",
      "Remix (IDE)",
      "React.js",
    ],
    "Team Name": "Ode to Code",
    "GitHub Link": "https://github.com/vermagaur851/Hackhazard-Healthcare",
  },
  "https://devfolio.co/submissions/securexpert-d765": {
    "Project Name": "SecureXpert",
    Description:
      "Our project, SecureXpert, aims to confront the vulnerabilities present in devices. With numerous ports on computer devices running various programs, many companies disable Windows Defender for legal or security purposes and use their own antivirus software, leaving their laptops susceptible to hackers exploiting these ports. Additionally, older generation laptops, commonly used by individuals with limited technical knowledge such as kids and senior citizens, often lack built-in Windows Defender protection. This situation allows ethical hackers to exploit these unprotected ports, potentially gaining complete control over the device. Our solution involves developing an application that provides users with a simple virtual device scan, empowering them to safeguard their devices effortlessly. Furthermore, our platform will educate users about cybersecurity, a crucial topic in today's digital landscape, aimed at reducing the prevalence of scams resulting from small security oversights.",
    "Technologies Used": [
      "JavaScript",
      "Socket.IO",
      "Python",
      "GitHub",
      "CSS3",
      "React.js",
      "HTML5\u200b",
      "JavaScript",
      "Socket.IO",
      "Python",
      "GitHub",
      "CSS3",
      "React.js",
      "HTML5\u200b",
    ],
    "Team Name": "H-INFINITY",
    "GitHub Link": "https://github.com/NishantKumar-2005/app",
  },
  "https://devfolio.co/submissions/skinsage-c8a3": {
    "Project Name": "SkinSage",
    Description:
      "Our project aims to address the medical services challenges in rural areas by developing a WebApp SkinSage. In rural areas medical services are very hard to get specifically dermatologists, due to the lack of development and neglection. SkinSage aims to tackle this issue by providing a platform to diagnose skin diseases and connecting doctors based on the users location. Users can diagnose and get medicines and also will be able to book appointments. Through this app our goal is to make dermatological services accessible and affordable so none of the under privileged goes neglected.",
    "Technologies Used": [
      "Django",
      "JavaScript",
      "TensorFlow",
      "PyTorch",
      "Python",
      "KNN",
      "Keras CNN",
      "HTML/CSS",
      "Django",
      "JavaScript",
      "TensorFlow",
      "PyTorch",
      "Python",
      "KNN",
      "Keras CNN",
      "HTML/CSS",
    ],
    "Team Name": "HyperText Assassins",
    "GitHub Link": "https://github.com/ErebusAJ/SkinSage",
  },
  "https://devfolio.co/submissions/my-air-visual-c572": {
    "Project Name": "My Air Visual",
    Description:
      "Users can utilize our air quality monitoring platform for a variety of purposes, enhancing their daily lives and ensuring a safer environment. With our platform, individuals can:",
    "Technologies Used": [
      "Redux",
      "Database - Mongodb",
      "Front End - React Js",
      "Back End - Node js expressJs",
      "Figma-UI/UX design",
      "Hardware - Arduino",
      "Blynk-web dashboard",
      "Redux",
      "Database - Mongodb",
      "Front End - React Js",
      "Back End - Node js expressJs",
      "Figma-UI/UX design",
      "Hardware - Arduino",
      "Blynk-web dashboard",
    ],
    "Team Name": "Tech Giants",
    "GitHub Link":
      "https://github.com/Aryan9901/AIR_QUALITY_MANAGEMENT_SOFTWARES",
  },
  "https://devfolio.co/submissions/before-deadline-token-57ce": {
    "Project Name": "Before Deadline Token",
    Description:
      "Students do not need to depend on non technical jobs to earn money, they can earn easily just by submitting their regular assignments on time.Students can earn their pocket money through this.Colleges can sort students based on their token history.Students can directly liquify money without the need of any thing else after they have reached a certain amount of tokens.",
    "Technologies Used": [
      "Cryptography",
      "Solidity",
      "React",
      "Smart Contract",
      "Web3",
      "Blockchain",
      "Tailwind CSS",
      "Replit",
      "Distributed Ledger",
      "security",
      "Cryptography",
      "Solidity",
      "React",
      "Smart Contract",
      "Web3",
      "Blockchain",
      "Tailwind CSS",
      "Replit",
      "Distributed Ledger",
      "security",
    ],
    "Team Name": "CU_Blockchain",
    "GitHub Link": "https://github.com/RIDAMSINHA/Deadline-Token-App",
  },
  "https://devfolio.co/submissions/bloodlink-b2b7": {
    "Project Name": "BloodLink",
    Description:
      "Our platform addresses critical issues in the blood donation ecosystem by providing a centralized hub for donors, recipients, and blood banks to connect and coordinate donations seamlessly, effectively tackling blood shortages and saving lives. Through peer-to-peer donations and a sophisticated matching algorithm, we increase the availability of blood for those in need while ensuring transparency and assurance with real-time tracking features. Incentives such as achievement badges and redeemable rewards foster donor engagement, while stringent data privacy and security measures instill trust and confidence among users, ultimately revolutionizing blood donation and improving healthcare outcomes.",
    "Technologies Used": [
      "React",
      "Node.js",
      "Postman",
      "JWT",
      "Google Maps API",
      "Express.js",
      "MongoDB Atlas",
      "MongoDB Compass",
      "React",
      "Node.js",
      "Postman",
      "JWT",
      "Google Maps API",
      "Express.js",
      "MongoDB Atlas",
      "MongoDB Compass",
    ],
    "Team Name": "JamnapaariCoders",
    "GitHub Link": "https://github.com/JatinGera27aug/BloodLink",
  },
  "https://devfolio.co/submissions/jeevanrekha-1e96": {
    "Project Name": "JeevanRekha",
    Description:
      "Our platform addresses critical challenges in accessing blood donations efficiently and safely.",
    "Technologies Used": [
      "React",
      "Firebase",
      "TensorFlow",
      "Raspberry Pi",
      "Python",
      "Hyperledger",
      "Tailwind CSS",
      "React",
      "Firebase",
      "TensorFlow",
      "Raspberry Pi",
      "Python",
      "Hyperledger",
      "Tailwind CSS",
    ],
    "Team Name": "Vendetta",
    "GitHub Link": "https://github.com/sanchitaa14/raktSanvha",
  },
  "https://devfolio.co/submissions/financial-friend-4e76": {
    "Project Name": "Financial Friend",
    Description:
      "Our project aims to tackle various obstacles to financial well-being. We address challenges such as low financial literacy, gender disparities in financial empowerment, and the digital divide in India. We also focus on reducing account dormancy, building trust in formal financial institutions, improving last-mile connectivity in rural areas, and increasing access to credit for small businesses and low-income individuals. Additionally, we emphasize the importance of designing tailored financial products that meet the specific needs of users, such as microloans, insurance, and savings, to ensure financial inclusion for all.",
    "Technologies Used": [
      "Node.js",
      "Flask",
      "REST API",
      "Python",
      "Natural language processing (NLP)",
      "MongoDB",
      "Cron Scheduler",
      "YouTube Data API",
      "Nodemailer",
      "React.js",
      "Node.js",
      "Flask",
      "REST API",
      "Python",
      "Natural language processing (NLP)",
      "MongoDB",
      "Cron Scheduler",
      "YouTube Data API",
      "Nodemailer",
      "React.js",
    ],
    "Team Name": "banzo",
    "GitHub Link": "https://github.com/BANZOM/FinancialFriend",
  },
  "https://devfolio.co/submissions/wealth-wise-a695": {
    "Project Name": "Wealth Wise",
    Description:
      "In today's world, the number one method of tax evasion is money laundering. Our AI is at the forefront of combating this pervasive issue by meticulously monitoring user transactions and activities across the platform. Through advanced algorithms and machine learning, it sifts through vast amounts of data to detect irregularities and anomalies indicative of potential money laundering schemes. By pinpointing suspicious transactions, our AI empowers administrators to swiftly intervene, verify, and if necessary, block such activities, thereby safeguarding the integrity of the financial ecosystem and ensuring compliance with regulations.",
    "Technologies Used": [
      "Node.js",
      "TensorFlow",
      "Python",
      "Flutter",
      "MongoDB Atlas",
      "AI/ML",
      "HTML/CSS",
      "sklearn",
      "Node.js",
      "TensorFlow",
      "Python",
      "Flutter",
      "MongoDB Atlas",
      "AI/ML",
      "HTML/CSS",
      "sklearn",
    ],
    "Team Name": "Codecrafters",
    "GitHub Link": "https://github.com/oweshkhan96/Wealth_wise",
  },
  "https://devfolio.co/submissions/breezecare-22bb": {
    "Project Name": "BreezeCare",
    Description:
      "Our project is a web app designed to tackle the problem of air quality in urban areas. introducing BreezeCare\u2014a user-centric initiative to tackles urban air quality issues by prioritizing community involvement. It makes complex data accessible by providing age-appropriate health guidance and region-specific environmental recommendations. By encouraging user engagement, the platform empowers both individuals and groups to take an active role in improving air quality. Designed with a user-friendly interface and multilingual support, BreezeCare inspires community participation and offers a simplified path for understanding and enhancing the local air quality environment.",
    "Technologies Used": [
      "CSS",
      "JavaScript",
      "Tailwind CSS",
      "React.js",
      "FETCH",
      "api-cn",
      "hooks",
      "CSS",
      "JavaScript",
      "Tailwind CSS",
      "React.js",
      "FETCH",
      "api-cn",
      "hooks",
    ],
    "Team Name": "Bit Brawlers",
    "GitHub Link": "https://github.com/Faizuddinq/breezecare",
  },
};
